# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test wm

on:
  pull_request:
  workflow_dispatch:
  push:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup
      run: |
        echo updating repos...
        sudo apt-get update -y 2>&1 > /dev/null
        echo installing dependencies...
        sudo apt-get install -y zsh gawk build-essential libdbus-glib-1-dev libgirepository1.0-dev 2>&1 > /dev/null
        echo updating pip...
        python -m pip install --upgrade pip 2>&1 > /dev/null
        pip install -r requirements.txt dbus-python 2>&1 > /dev/null
        echo running setup.sh...
        chmod +x scripts/setup.sh 2>&1 > /dev/null
        zsh scripts/setup.sh 2>&1 > /dev/null
        echo installing testing tools...
        sudo apt-get install -y xvfb xserver-xephyr x11-apps xterm 2>&1 > /dev/null
    - name: Run tests
      run: |
        xvfb-run python test.py
